// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/customer/v1/customer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Customer_CreateCustomer_FullMethodName           = "/api.customer.v1.Customer/CreateCustomer"
	Customer_CreateEmail_FullMethodName              = "/api.customer.v1.Customer/CreateEmail"
	Customer_CreatePhoneNumber_FullMethodName        = "/api.customer.v1.Customer/CreatePhoneNumber"
	Customer_UpdateCustomer_FullMethodName           = "/api.customer.v1.Customer/UpdateCustomer"
	Customer_DeleteCustomer_FullMethodName           = "/api.customer.v1.Customer/DeleteCustomer"
	Customer_ListCustomer_FullMethodName             = "/api.customer.v1.Customer/ListCustomer"
	Customer_CreateAddress_FullMethodName            = "/api.customer.v1.Customer/CreateAddress"
	Customer_ListAddress_FullMethodName              = "/api.customer.v1.Customer/ListAddress"
	Customer_ListPhoneNumber_FullMethodName          = "/api.customer.v1.Customer/ListPhoneNumber"
	Customer_ListEmail_FullMethodName                = "/api.customer.v1.Customer/ListEmail"
	Customer_GetCustomer_FullMethodName              = "/api.customer.v1.Customer/GetCustomer"
	Customer_GetCustomerByEmail_FullMethodName       = "/api.customer.v1.Customer/GetCustomerByEmail"
	Customer_GetCustomerByPhoneNumber_FullMethodName = "/api.customer.v1.Customer/GetCustomerByPhoneNumber"
	Customer_DeletePhoneNumber_FullMethodName        = "/api.customer.v1.Customer/DeletePhoneNumber"
	Customer_DeleteAddress_FullMethodName            = "/api.customer.v1.Customer/DeleteAddress"
	Customer_DeleteEmail_FullMethodName              = "/api.customer.v1.Customer/DeleteEmail"
)

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerClient interface {
	CreateCustomer(ctx context.Context, in *CreateCustomerReq, opts ...grpc.CallOption) (*CreateCustomerReply, error)
	CreateEmail(ctx context.Context, in *CreateEmailReq, opts ...grpc.CallOption) (*CreateEmailReply, error)
	CreatePhoneNumber(ctx context.Context, in *CreatePhoneNumberReq, opts ...grpc.CallOption) (*CreatePhoneNumberReply, error)
	UpdateCustomer(ctx context.Context, in *UpdateCustomerReq, opts ...grpc.CallOption) (*UpdateCustomerReply, error)
	DeleteCustomer(ctx context.Context, in *DeleteCustomerReq, opts ...grpc.CallOption) (*DeleteCustomerReply, error)
	ListCustomer(ctx context.Context, in *ListCustomerReq, opts ...grpc.CallOption) (*ListCustomerReply, error)
	CreateAddress(ctx context.Context, in *CreateAddressReq, opts ...grpc.CallOption) (*CreateAddressReply, error)
	ListAddress(ctx context.Context, in *ListAddressReq, opts ...grpc.CallOption) (*ListAddressReply, error)
	ListPhoneNumber(ctx context.Context, in *ListPhoneNumberReq, opts ...grpc.CallOption) (*ListPhoneNumberReply, error)
	ListEmail(ctx context.Context, in *ListEmailReq, opts ...grpc.CallOption) (*ListEmailReply, error)
	GetCustomer(ctx context.Context, in *GetCustomerReq, opts ...grpc.CallOption) (*GetCustomerReply, error)
	GetCustomerByEmail(ctx context.Context, in *GetCustomerByEmailReq, opts ...grpc.CallOption) (*GetCustomerByEmailReply, error)
	GetCustomerByPhoneNumber(ctx context.Context, in *GetCustomerByPhoneNumberReq, opts ...grpc.CallOption) (*GetCustomerByPhoneNumberReply, error)
	DeletePhoneNumber(ctx context.Context, in *DeletePhoneNumberReq, opts ...grpc.CallOption) (*DeletePhoneNumberReply, error)
	DeleteAddress(ctx context.Context, in *DeleteAddressReq, opts ...grpc.CallOption) (*DeleteAddressReply, error)
	DeleteEmail(ctx context.Context, in *DeleteEmailReq, opts ...grpc.CallOption) (*DeleteEmailReply, error)
}

type customerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerClient(cc grpc.ClientConnInterface) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) CreateCustomer(ctx context.Context, in *CreateCustomerReq, opts ...grpc.CallOption) (*CreateCustomerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCustomerReply)
	err := c.cc.Invoke(ctx, Customer_CreateCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) CreateEmail(ctx context.Context, in *CreateEmailReq, opts ...grpc.CallOption) (*CreateEmailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEmailReply)
	err := c.cc.Invoke(ctx, Customer_CreateEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) CreatePhoneNumber(ctx context.Context, in *CreatePhoneNumberReq, opts ...grpc.CallOption) (*CreatePhoneNumberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePhoneNumberReply)
	err := c.cc.Invoke(ctx, Customer_CreatePhoneNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) UpdateCustomer(ctx context.Context, in *UpdateCustomerReq, opts ...grpc.CallOption) (*UpdateCustomerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCustomerReply)
	err := c.cc.Invoke(ctx, Customer_UpdateCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DeleteCustomer(ctx context.Context, in *DeleteCustomerReq, opts ...grpc.CallOption) (*DeleteCustomerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCustomerReply)
	err := c.cc.Invoke(ctx, Customer_DeleteCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ListCustomer(ctx context.Context, in *ListCustomerReq, opts ...grpc.CallOption) (*ListCustomerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCustomerReply)
	err := c.cc.Invoke(ctx, Customer_ListCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) CreateAddress(ctx context.Context, in *CreateAddressReq, opts ...grpc.CallOption) (*CreateAddressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAddressReply)
	err := c.cc.Invoke(ctx, Customer_CreateAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ListAddress(ctx context.Context, in *ListAddressReq, opts ...grpc.CallOption) (*ListAddressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAddressReply)
	err := c.cc.Invoke(ctx, Customer_ListAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ListPhoneNumber(ctx context.Context, in *ListPhoneNumberReq, opts ...grpc.CallOption) (*ListPhoneNumberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPhoneNumberReply)
	err := c.cc.Invoke(ctx, Customer_ListPhoneNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ListEmail(ctx context.Context, in *ListEmailReq, opts ...grpc.CallOption) (*ListEmailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEmailReply)
	err := c.cc.Invoke(ctx, Customer_ListEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomer(ctx context.Context, in *GetCustomerReq, opts ...grpc.CallOption) (*GetCustomerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerReply)
	err := c.cc.Invoke(ctx, Customer_GetCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomerByEmail(ctx context.Context, in *GetCustomerByEmailReq, opts ...grpc.CallOption) (*GetCustomerByEmailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerByEmailReply)
	err := c.cc.Invoke(ctx, Customer_GetCustomerByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomerByPhoneNumber(ctx context.Context, in *GetCustomerByPhoneNumberReq, opts ...grpc.CallOption) (*GetCustomerByPhoneNumberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomerByPhoneNumberReply)
	err := c.cc.Invoke(ctx, Customer_GetCustomerByPhoneNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DeletePhoneNumber(ctx context.Context, in *DeletePhoneNumberReq, opts ...grpc.CallOption) (*DeletePhoneNumberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePhoneNumberReply)
	err := c.cc.Invoke(ctx, Customer_DeletePhoneNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DeleteAddress(ctx context.Context, in *DeleteAddressReq, opts ...grpc.CallOption) (*DeleteAddressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAddressReply)
	err := c.cc.Invoke(ctx, Customer_DeleteAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DeleteEmail(ctx context.Context, in *DeleteEmailReq, opts ...grpc.CallOption) (*DeleteEmailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEmailReply)
	err := c.cc.Invoke(ctx, Customer_DeleteEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
// All implementations must embed UnimplementedCustomerServer
// for forward compatibility.
type CustomerServer interface {
	CreateCustomer(context.Context, *CreateCustomerReq) (*CreateCustomerReply, error)
	CreateEmail(context.Context, *CreateEmailReq) (*CreateEmailReply, error)
	CreatePhoneNumber(context.Context, *CreatePhoneNumberReq) (*CreatePhoneNumberReply, error)
	UpdateCustomer(context.Context, *UpdateCustomerReq) (*UpdateCustomerReply, error)
	DeleteCustomer(context.Context, *DeleteCustomerReq) (*DeleteCustomerReply, error)
	ListCustomer(context.Context, *ListCustomerReq) (*ListCustomerReply, error)
	CreateAddress(context.Context, *CreateAddressReq) (*CreateAddressReply, error)
	ListAddress(context.Context, *ListAddressReq) (*ListAddressReply, error)
	ListPhoneNumber(context.Context, *ListPhoneNumberReq) (*ListPhoneNumberReply, error)
	ListEmail(context.Context, *ListEmailReq) (*ListEmailReply, error)
	GetCustomer(context.Context, *GetCustomerReq) (*GetCustomerReply, error)
	GetCustomerByEmail(context.Context, *GetCustomerByEmailReq) (*GetCustomerByEmailReply, error)
	GetCustomerByPhoneNumber(context.Context, *GetCustomerByPhoneNumberReq) (*GetCustomerByPhoneNumberReply, error)
	DeletePhoneNumber(context.Context, *DeletePhoneNumberReq) (*DeletePhoneNumberReply, error)
	DeleteAddress(context.Context, *DeleteAddressReq) (*DeleteAddressReply, error)
	DeleteEmail(context.Context, *DeleteEmailReq) (*DeleteEmailReply, error)
	mustEmbedUnimplementedCustomerServer()
}

// UnimplementedCustomerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerServer struct{}

func (UnimplementedCustomerServer) CreateCustomer(context.Context, *CreateCustomerReq) (*CreateCustomerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedCustomerServer) CreateEmail(context.Context, *CreateEmailReq) (*CreateEmailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEmail not implemented")
}
func (UnimplementedCustomerServer) CreatePhoneNumber(context.Context, *CreatePhoneNumberReq) (*CreatePhoneNumberReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePhoneNumber not implemented")
}
func (UnimplementedCustomerServer) UpdateCustomer(context.Context, *UpdateCustomerReq) (*UpdateCustomerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCustomer not implemented")
}
func (UnimplementedCustomerServer) DeleteCustomer(context.Context, *DeleteCustomerReq) (*DeleteCustomerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCustomer not implemented")
}
func (UnimplementedCustomerServer) ListCustomer(context.Context, *ListCustomerReq) (*ListCustomerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCustomer not implemented")
}
func (UnimplementedCustomerServer) CreateAddress(context.Context, *CreateAddressReq) (*CreateAddressReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAddress not implemented")
}
func (UnimplementedCustomerServer) ListAddress(context.Context, *ListAddressReq) (*ListAddressReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAddress not implemented")
}
func (UnimplementedCustomerServer) ListPhoneNumber(context.Context, *ListPhoneNumberReq) (*ListPhoneNumberReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPhoneNumber not implemented")
}
func (UnimplementedCustomerServer) ListEmail(context.Context, *ListEmailReq) (*ListEmailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEmail not implemented")
}
func (UnimplementedCustomerServer) GetCustomer(context.Context, *GetCustomerReq) (*GetCustomerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomer not implemented")
}
func (UnimplementedCustomerServer) GetCustomerByEmail(context.Context, *GetCustomerByEmailReq) (*GetCustomerByEmailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomerByEmail not implemented")
}
func (UnimplementedCustomerServer) GetCustomerByPhoneNumber(context.Context, *GetCustomerByPhoneNumberReq) (*GetCustomerByPhoneNumberReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomerByPhoneNumber not implemented")
}
func (UnimplementedCustomerServer) DeletePhoneNumber(context.Context, *DeletePhoneNumberReq) (*DeletePhoneNumberReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePhoneNumber not implemented")
}
func (UnimplementedCustomerServer) DeleteAddress(context.Context, *DeleteAddressReq) (*DeleteAddressReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAddress not implemented")
}
func (UnimplementedCustomerServer) DeleteEmail(context.Context, *DeleteEmailReq) (*DeleteEmailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEmail not implemented")
}
func (UnimplementedCustomerServer) mustEmbedUnimplementedCustomerServer() {}
func (UnimplementedCustomerServer) testEmbeddedByValue()                  {}

// UnsafeCustomerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServer will
// result in compilation errors.
type UnsafeCustomerServer interface {
	mustEmbedUnimplementedCustomerServer()
}

func RegisterCustomerServer(s grpc.ServiceRegistrar, srv CustomerServer) {
	// If the following call panics, it indicates UnimplementedCustomerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Customer_ServiceDesc, srv)
}

func _Customer_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_CreateCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CreateCustomer(ctx, req.(*CreateCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_CreateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CreateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_CreateEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CreateEmail(ctx, req.(*CreateEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_CreatePhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePhoneNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CreatePhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_CreatePhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CreatePhoneNumber(ctx, req.(*CreatePhoneNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_UpdateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).UpdateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_UpdateCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).UpdateCustomer(ctx, req.(*UpdateCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_DeleteCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).DeleteCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_DeleteCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).DeleteCustomer(ctx, req.(*DeleteCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_ListCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).ListCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_ListCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).ListCustomer(ctx, req.(*ListCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_CreateAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CreateAddress(ctx, req.(*CreateAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_ListAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).ListAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_ListAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).ListAddress(ctx, req.(*ListAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_ListPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPhoneNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).ListPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_ListPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).ListPhoneNumber(ctx, req.(*ListPhoneNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_ListEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).ListEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_ListEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).ListEmail(ctx, req.(*ListEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_GetCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomer(ctx, req.(*GetCustomerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomerByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerByEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomerByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_GetCustomerByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomerByEmail(ctx, req.(*GetCustomerByEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomerByPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerByPhoneNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomerByPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_GetCustomerByPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomerByPhoneNumber(ctx, req.(*GetCustomerByPhoneNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_DeletePhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePhoneNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).DeletePhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_DeletePhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).DeletePhoneNumber(ctx, req.(*DeletePhoneNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_DeleteAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).DeleteAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_DeleteAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).DeleteAddress(ctx, req.(*DeleteAddressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_DeleteEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).DeleteEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Customer_DeleteEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).DeleteEmail(ctx, req.(*DeleteEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Customer_ServiceDesc is the grpc.ServiceDesc for Customer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Customer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.customer.v1.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _Customer_CreateCustomer_Handler,
		},
		{
			MethodName: "CreateEmail",
			Handler:    _Customer_CreateEmail_Handler,
		},
		{
			MethodName: "CreatePhoneNumber",
			Handler:    _Customer_CreatePhoneNumber_Handler,
		},
		{
			MethodName: "UpdateCustomer",
			Handler:    _Customer_UpdateCustomer_Handler,
		},
		{
			MethodName: "DeleteCustomer",
			Handler:    _Customer_DeleteCustomer_Handler,
		},
		{
			MethodName: "ListCustomer",
			Handler:    _Customer_ListCustomer_Handler,
		},
		{
			MethodName: "CreateAddress",
			Handler:    _Customer_CreateAddress_Handler,
		},
		{
			MethodName: "ListAddress",
			Handler:    _Customer_ListAddress_Handler,
		},
		{
			MethodName: "ListPhoneNumber",
			Handler:    _Customer_ListPhoneNumber_Handler,
		},
		{
			MethodName: "ListEmail",
			Handler:    _Customer_ListEmail_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _Customer_GetCustomer_Handler,
		},
		{
			MethodName: "GetCustomerByEmail",
			Handler:    _Customer_GetCustomerByEmail_Handler,
		},
		{
			MethodName: "GetCustomerByPhoneNumber",
			Handler:    _Customer_GetCustomerByPhoneNumber_Handler,
		},
		{
			MethodName: "DeletePhoneNumber",
			Handler:    _Customer_DeletePhoneNumber_Handler,
		},
		{
			MethodName: "DeleteAddress",
			Handler:    _Customer_DeleteAddress_Handler,
		},
		{
			MethodName: "DeleteEmail",
			Handler:    _Customer_DeleteEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/customer/v1/customer.proto",
}
