// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/customer/v1/customer.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCustomerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerReq) Reset() {
	*x = GetCustomerReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerReq) ProtoMessage() {}

func (x *GetCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerReq.ProtoReflect.Descriptor instead.
func (*GetCustomerReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *GetCustomerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumbers  []string               `protobuf:"bytes,3,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Emails        []string               `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	Addresses     []string               `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerReply) Reset() {
	*x = GetCustomerReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerReply) ProtoMessage() {}

func (x *GetCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerReply.ProtoReflect.Descriptor instead.
func (*GetCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomerReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCustomerReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCustomerReply) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

func (x *GetCustomerReply) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *GetCustomerReply) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetCustomerReply) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type GetCustomerByEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerByEmailReq) Reset() {
	*x = GetCustomerByEmailReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerByEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerByEmailReq) ProtoMessage() {}

func (x *GetCustomerByEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerByEmailReq.ProtoReflect.Descriptor instead.
func (*GetCustomerByEmailReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{2}
}

func (x *GetCustomerByEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetCustomerByEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumbers  []string               `protobuf:"bytes,3,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Emails        []string               `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	Addresses     []string               `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerByEmailReply) Reset() {
	*x = GetCustomerByEmailReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerByEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerByEmailReply) ProtoMessage() {}

func (x *GetCustomerByEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerByEmailReply.ProtoReflect.Descriptor instead.
func (*GetCustomerByEmailReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomerByEmailReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCustomerByEmailReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCustomerByEmailReply) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

func (x *GetCustomerByEmailReply) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *GetCustomerByEmailReply) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetCustomerByEmailReply) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type GetCustomerByPhoneNumberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerByPhoneNumberReq) Reset() {
	*x = GetCustomerByPhoneNumberReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerByPhoneNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerByPhoneNumberReq) ProtoMessage() {}

func (x *GetCustomerByPhoneNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerByPhoneNumberReq.ProtoReflect.Descriptor instead.
func (*GetCustomerByPhoneNumberReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerByPhoneNumberReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetCustomerByPhoneNumberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumbers  []string               `protobuf:"bytes,3,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Emails        []string               `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	Addresses     []string               `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerByPhoneNumberReply) Reset() {
	*x = GetCustomerByPhoneNumberReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerByPhoneNumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerByPhoneNumberReply) ProtoMessage() {}

func (x *GetCustomerByPhoneNumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerByPhoneNumberReply.ProtoReflect.Descriptor instead.
func (*GetCustomerByPhoneNumberReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomerByPhoneNumberReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCustomerByPhoneNumberReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCustomerByPhoneNumberReply) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

func (x *GetCustomerByPhoneNumberReply) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *GetCustomerByPhoneNumberReply) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetCustomerByPhoneNumberReply) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type CreateCustomerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,2,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerReq) Reset() {
	*x = CreateCustomerReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerReq) ProtoMessage() {}

func (x *CreateCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerReq.ProtoReflect.Descriptor instead.
func (*CreateCustomerReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCustomerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCustomerReq) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type CreateCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerReply) Reset() {
	*x = CreateCustomerReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerReply) ProtoMessage() {}

func (x *CreateCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerReply.ProtoReflect.Descriptor instead.
func (*CreateCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCustomerReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateCustomerReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCustomerReply) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type UpdateCustomerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerReq) Reset() {
	*x = UpdateCustomerReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerReq) ProtoMessage() {}

func (x *UpdateCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerReq.ProtoReflect.Descriptor instead.
func (*UpdateCustomerReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCustomerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCustomerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCustomerReq) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type UpdateCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumbers  []string               `protobuf:"bytes,3,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Emails        []string               `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	Addresses     []string               `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerReply) Reset() {
	*x = UpdateCustomerReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerReply) ProtoMessage() {}

func (x *UpdateCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerReply.ProtoReflect.Descriptor instead.
func (*UpdateCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCustomerReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCustomerReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCustomerReply) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

func (x *UpdateCustomerReply) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *UpdateCustomerReply) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *UpdateCustomerReply) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type DeleteCustomerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerReq) Reset() {
	*x = DeleteCustomerReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerReq) ProtoMessage() {}

func (x *DeleteCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerReq.ProtoReflect.Descriptor instead.
func (*DeleteCustomerReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCustomerReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerReply) Reset() {
	*x = DeleteCustomerReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerReply) ProtoMessage() {}

func (x *DeleteCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerReply.ProtoReflect.Descriptor instead.
func (*DeleteCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCustomerReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreatePhoneNumberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePhoneNumberReq) Reset() {
	*x = CreatePhoneNumberReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePhoneNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhoneNumberReq) ProtoMessage() {}

func (x *CreatePhoneNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhoneNumberReq.ProtoReflect.Descriptor instead.
func (*CreatePhoneNumberReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePhoneNumberReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreatePhoneNumberReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreatePhoneNumberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePhoneNumberReply) Reset() {
	*x = CreatePhoneNumberReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePhoneNumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhoneNumberReply) ProtoMessage() {}

func (x *CreatePhoneNumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhoneNumberReply.ProtoReflect.Descriptor instead.
func (*CreatePhoneNumberReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePhoneNumberReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatePhoneNumberReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreatePhoneNumberReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ListPhoneNumberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhoneNumberReq) Reset() {
	*x = ListPhoneNumberReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhoneNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhoneNumberReq) ProtoMessage() {}

func (x *ListPhoneNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhoneNumberReq.ProtoReflect.Descriptor instead.
func (*ListPhoneNumberReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{14}
}

func (x *ListPhoneNumberReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type ListPhoneNumberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumbers  []string               `protobuf:"bytes,1,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhoneNumberReply) Reset() {
	*x = ListPhoneNumberReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhoneNumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhoneNumberReply) ProtoMessage() {}

func (x *ListPhoneNumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhoneNumberReply.ProtoReflect.Descriptor instead.
func (*ListPhoneNumberReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{15}
}

func (x *ListPhoneNumberReply) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

type DeletePhoneNumberReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePhoneNumberReq) Reset() {
	*x = DeletePhoneNumberReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePhoneNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePhoneNumberReq) ProtoMessage() {}

func (x *DeletePhoneNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePhoneNumberReq.ProtoReflect.Descriptor instead.
func (*DeletePhoneNumberReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{16}
}

func (x *DeletePhoneNumberReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *DeletePhoneNumberReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type DeletePhoneNumberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePhoneNumberReply) Reset() {
	*x = DeletePhoneNumberReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePhoneNumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePhoneNumberReply) ProtoMessage() {}

func (x *DeletePhoneNumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePhoneNumberReply.ProtoReflect.Descriptor instead.
func (*DeletePhoneNumberReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{17}
}

func (x *DeletePhoneNumberReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailReq) Reset() {
	*x = CreateEmailReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailReq) ProtoMessage() {}

func (x *CreateEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailReq.ProtoReflect.Descriptor instead.
func (*CreateEmailReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{18}
}

func (x *CreateEmailReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailReply) Reset() {
	*x = CreateEmailReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailReply) ProtoMessage() {}

func (x *CreateEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailReply.ProtoReflect.Descriptor instead.
func (*CreateEmailReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{19}
}

func (x *CreateEmailReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateEmailReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateEmailReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailReq) Reset() {
	*x = ListEmailReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailReq) ProtoMessage() {}

func (x *ListEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailReq.ProtoReflect.Descriptor instead.
func (*ListEmailReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{20}
}

func (x *ListEmailReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type ListEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailReply) Reset() {
	*x = ListEmailReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailReply) ProtoMessage() {}

func (x *ListEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailReply.ProtoReflect.Descriptor instead.
func (*ListEmailReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{21}
}

func (x *ListEmailReply) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

type DeleteEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailReq) Reset() {
	*x = DeleteEmailReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailReq) ProtoMessage() {}

func (x *DeleteEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailReq.ProtoReflect.Descriptor instead.
func (*DeleteEmailReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteEmailReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *DeleteEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DeleteEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailReply) Reset() {
	*x = DeleteEmailReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailReply) ProtoMessage() {}

func (x *DeleteEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailReply.ProtoReflect.Descriptor instead.
func (*DeleteEmailReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteEmailReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressReq) Reset() {
	*x = CreateAddressReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressReq) ProtoMessage() {}

func (x *CreateAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressReq.ProtoReflect.Descriptor instead.
func (*CreateAddressReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{24}
}

func (x *CreateAddressReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateAddressReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressReply) Reset() {
	*x = CreateAddressReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressReply) ProtoMessage() {}

func (x *CreateAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressReply.ProtoReflect.Descriptor instead.
func (*CreateAddressReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{25}
}

func (x *CreateAddressReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateAddressReply) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReq) Reset() {
	*x = ListAddressReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReq) ProtoMessage() {}

func (x *ListAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReq.ProtoReflect.Descriptor instead.
func (*ListAddressReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{26}
}

func (x *ListAddressReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type ListAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReply) Reset() {
	*x = ListAddressReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReply) ProtoMessage() {}

func (x *ListAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReply.ProtoReflect.Descriptor instead.
func (*ListAddressReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{27}
}

func (x *ListAddressReply) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type DeleteAddressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressReq) Reset() {
	*x = DeleteAddressReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressReq) ProtoMessage() {}

func (x *DeleteAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressReq.ProtoReflect.Descriptor instead.
func (*DeleteAddressReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteAddressReq) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *DeleteAddressReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeleteAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressReply) Reset() {
	*x = DeleteAddressReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressReply) ProtoMessage() {}

func (x *DeleteAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressReply.ProtoReflect.Descriptor instead.
func (*DeleteAddressReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteAddressReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCustomerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerReq) Reset() {
	*x = ListCustomerReq{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerReq) ProtoMessage() {}

func (x *ListCustomerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerReq.ProtoReflect.Descriptor instead.
func (*ListCustomerReq) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{30}
}

type ListCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*GetCustomerReply    `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerReply) Reset() {
	*x = ListCustomerReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerReply) ProtoMessage() {}

func (x *ListCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerReply.ProtoReflect.Descriptor instead.
func (*ListCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{31}
}

func (x *ListCustomerReply) GetCustomers() []*GetCustomerReply {
	if x != nil {
		return x.Customers
	}
	return nil
}

var File_api_customer_v1_customer_proto protoreflect.FileDescriptor

const file_api_customer_v1_customer_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/customer/v1/customer.proto\x12\x0fapi.customer.v1\x1a\x1cgoogle/api/annotations.proto\" \n" +
	"\x0eGetCustomerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb5\x01\n" +
	"\x10GetCustomerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rphone_numbers\x18\x03 \x03(\tR\fphoneNumbers\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses\x12\"\n" +
	"\rdate_of_birth\x18\x06 \x01(\tR\vdateOfBirth\"-\n" +
	"\x15GetCustomerByEmailReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xbc\x01\n" +
	"\x17GetCustomerByEmailReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rphone_numbers\x18\x03 \x03(\tR\fphoneNumbers\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses\x12\"\n" +
	"\rdate_of_birth\x18\x06 \x01(\tR\vdateOfBirth\"3\n" +
	"\x1bGetCustomerByPhoneNumberReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"\xc2\x01\n" +
	"\x1dGetCustomerByPhoneNumberReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rphone_numbers\x18\x03 \x03(\tR\fphoneNumbers\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses\x12\"\n" +
	"\rdate_of_birth\x18\x06 \x01(\tR\vdateOfBirth\"K\n" +
	"\x11CreateCustomerReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\rdate_of_birth\x18\x02 \x01(\tR\vdateOfBirth\"]\n" +
	"\x13CreateCustomerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\"[\n" +
	"\x11UpdateCustomerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\"\xb8\x01\n" +
	"\x13UpdateCustomerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rphone_numbers\x18\x03 \x03(\tR\fphoneNumbers\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses\x12\"\n" +
	"\rdate_of_birth\x18\x06 \x01(\tR\vdateOfBirth\"#\n" +
	"\x11DeleteCustomerReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteCustomerReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x14CreatePhoneNumberReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"_\n" +
	"\x16CreatePhoneNumberReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"5\n" +
	"\x12ListPhoneNumberReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\";\n" +
	"\x14ListPhoneNumberReply\x12#\n" +
	"\rphone_numbers\x18\x01 \x03(\tR\fphoneNumbers\"M\n" +
	"\x14DeletePhoneNumberReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"2\n" +
	"\x16DeletePhoneNumberReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x0eCreateEmailReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"Y\n" +
	"\x10CreateEmailReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"/\n" +
	"\fListEmailReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\"(\n" +
	"\x0eListEmailReply\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails\"G\n" +
	"\x0eDeleteEmailReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\",\n" +
	"\x10DeleteEmailReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x10CreateAddressReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"_\n" +
	"\x12CreateAddressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"1\n" +
	"\x0eListAddressReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\"0\n" +
	"\x10ListAddressReply\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"M\n" +
	"\x10DeleteAddressReq\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x03R\n" +
	"customerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\".\n" +
	"\x12DeleteAddressReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fListCustomerReq\"T\n" +
	"\x11ListCustomerReply\x12?\n" +
	"\tcustomers\x18\x01 \x03(\v2!.api.customer.v1.GetCustomerReplyR\tcustomers2\xea\v\n" +
	"\bCustomer\x12\\\n" +
	"\x0eCreateCustomer\x12\".api.customer.v1.CreateCustomerReq\x1a$.api.customer.v1.CreateCustomerReply\"\x00\x12S\n" +
	"\vCreateEmail\x12\x1f.api.customer.v1.CreateEmailReq\x1a!.api.customer.v1.CreateEmailReply\"\x00\x12e\n" +
	"\x11CreatePhoneNumber\x12%.api.customer.v1.CreatePhoneNumberReq\x1a'.api.customer.v1.CreatePhoneNumberReply\"\x00\x12\\\n" +
	"\x0eUpdateCustomer\x12\".api.customer.v1.UpdateCustomerReq\x1a$.api.customer.v1.UpdateCustomerReply\"\x00\x12\\\n" +
	"\x0eDeleteCustomer\x12\".api.customer.v1.DeleteCustomerReq\x1a$.api.customer.v1.DeleteCustomerReply\"\x00\x12V\n" +
	"\fListCustomer\x12 .api.customer.v1.ListCustomerReq\x1a\".api.customer.v1.ListCustomerReply\"\x00\x12Y\n" +
	"\rCreateAddress\x12!.api.customer.v1.CreateAddressReq\x1a#.api.customer.v1.CreateAddressReply\"\x00\x12S\n" +
	"\vListAddress\x12\x1f.api.customer.v1.ListAddressReq\x1a!.api.customer.v1.ListAddressReply\"\x00\x12_\n" +
	"\x0fListPhoneNumber\x12#.api.customer.v1.ListPhoneNumberReq\x1a%.api.customer.v1.ListPhoneNumberReply\"\x00\x12M\n" +
	"\tListEmail\x12\x1d.api.customer.v1.ListEmailReq\x1a\x1f.api.customer.v1.ListEmailReply\"\x00\x12S\n" +
	"\vGetCustomer\x12\x1f.api.customer.v1.GetCustomerReq\x1a!.api.customer.v1.GetCustomerReply\"\x00\x12h\n" +
	"\x12GetCustomerByEmail\x12&.api.customer.v1.GetCustomerByEmailReq\x1a(.api.customer.v1.GetCustomerByEmailReply\"\x00\x12z\n" +
	"\x18GetCustomerByPhoneNumber\x12,.api.customer.v1.GetCustomerByPhoneNumberReq\x1a..api.customer.v1.GetCustomerByPhoneNumberReply\"\x00\x12e\n" +
	"\x11DeletePhoneNumber\x12%.api.customer.v1.DeletePhoneNumberReq\x1a'.api.customer.v1.DeletePhoneNumberReply\"\x00\x12Y\n" +
	"\rDeleteAddress\x12!.api.customer.v1.DeleteAddressReq\x1a#.api.customer.v1.DeleteAddressReply\"\x00\x12S\n" +
	"\vDeleteEmail\x12\x1f.api.customer.v1.DeleteEmailReq\x1a!.api.customer.v1.DeleteEmailReply\"\x00B\x1dZ\x1bcustomer/api/customer/v1;v1b\x06proto3"

var (
	file_api_customer_v1_customer_proto_rawDescOnce sync.Once
	file_api_customer_v1_customer_proto_rawDescData []byte
)

func file_api_customer_v1_customer_proto_rawDescGZIP() []byte {
	file_api_customer_v1_customer_proto_rawDescOnce.Do(func() {
		file_api_customer_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_customer_v1_customer_proto_rawDesc), len(file_api_customer_v1_customer_proto_rawDesc)))
	})
	return file_api_customer_v1_customer_proto_rawDescData
}

var file_api_customer_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_customer_v1_customer_proto_goTypes = []any{
	(*GetCustomerReq)(nil),                // 0: api.customer.v1.GetCustomerReq
	(*GetCustomerReply)(nil),              // 1: api.customer.v1.GetCustomerReply
	(*GetCustomerByEmailReq)(nil),         // 2: api.customer.v1.GetCustomerByEmailReq
	(*GetCustomerByEmailReply)(nil),       // 3: api.customer.v1.GetCustomerByEmailReply
	(*GetCustomerByPhoneNumberReq)(nil),   // 4: api.customer.v1.GetCustomerByPhoneNumberReq
	(*GetCustomerByPhoneNumberReply)(nil), // 5: api.customer.v1.GetCustomerByPhoneNumberReply
	(*CreateCustomerReq)(nil),             // 6: api.customer.v1.CreateCustomerReq
	(*CreateCustomerReply)(nil),           // 7: api.customer.v1.CreateCustomerReply
	(*UpdateCustomerReq)(nil),             // 8: api.customer.v1.UpdateCustomerReq
	(*UpdateCustomerReply)(nil),           // 9: api.customer.v1.UpdateCustomerReply
	(*DeleteCustomerReq)(nil),             // 10: api.customer.v1.DeleteCustomerReq
	(*DeleteCustomerReply)(nil),           // 11: api.customer.v1.DeleteCustomerReply
	(*CreatePhoneNumberReq)(nil),          // 12: api.customer.v1.CreatePhoneNumberReq
	(*CreatePhoneNumberReply)(nil),        // 13: api.customer.v1.CreatePhoneNumberReply
	(*ListPhoneNumberReq)(nil),            // 14: api.customer.v1.ListPhoneNumberReq
	(*ListPhoneNumberReply)(nil),          // 15: api.customer.v1.ListPhoneNumberReply
	(*DeletePhoneNumberReq)(nil),          // 16: api.customer.v1.DeletePhoneNumberReq
	(*DeletePhoneNumberReply)(nil),        // 17: api.customer.v1.DeletePhoneNumberReply
	(*CreateEmailReq)(nil),                // 18: api.customer.v1.CreateEmailReq
	(*CreateEmailReply)(nil),              // 19: api.customer.v1.CreateEmailReply
	(*ListEmailReq)(nil),                  // 20: api.customer.v1.ListEmailReq
	(*ListEmailReply)(nil),                // 21: api.customer.v1.ListEmailReply
	(*DeleteEmailReq)(nil),                // 22: api.customer.v1.DeleteEmailReq
	(*DeleteEmailReply)(nil),              // 23: api.customer.v1.DeleteEmailReply
	(*CreateAddressReq)(nil),              // 24: api.customer.v1.CreateAddressReq
	(*CreateAddressReply)(nil),            // 25: api.customer.v1.CreateAddressReply
	(*ListAddressReq)(nil),                // 26: api.customer.v1.ListAddressReq
	(*ListAddressReply)(nil),              // 27: api.customer.v1.ListAddressReply
	(*DeleteAddressReq)(nil),              // 28: api.customer.v1.DeleteAddressReq
	(*DeleteAddressReply)(nil),            // 29: api.customer.v1.DeleteAddressReply
	(*ListCustomerReq)(nil),               // 30: api.customer.v1.ListCustomerReq
	(*ListCustomerReply)(nil),             // 31: api.customer.v1.ListCustomerReply
}
var file_api_customer_v1_customer_proto_depIdxs = []int32{
	1,  // 0: api.customer.v1.ListCustomerReply.customers:type_name -> api.customer.v1.GetCustomerReply
	6,  // 1: api.customer.v1.Customer.CreateCustomer:input_type -> api.customer.v1.CreateCustomerReq
	18, // 2: api.customer.v1.Customer.CreateEmail:input_type -> api.customer.v1.CreateEmailReq
	12, // 3: api.customer.v1.Customer.CreatePhoneNumber:input_type -> api.customer.v1.CreatePhoneNumberReq
	8,  // 4: api.customer.v1.Customer.UpdateCustomer:input_type -> api.customer.v1.UpdateCustomerReq
	10, // 5: api.customer.v1.Customer.DeleteCustomer:input_type -> api.customer.v1.DeleteCustomerReq
	30, // 6: api.customer.v1.Customer.ListCustomer:input_type -> api.customer.v1.ListCustomerReq
	24, // 7: api.customer.v1.Customer.CreateAddress:input_type -> api.customer.v1.CreateAddressReq
	26, // 8: api.customer.v1.Customer.ListAddress:input_type -> api.customer.v1.ListAddressReq
	14, // 9: api.customer.v1.Customer.ListPhoneNumber:input_type -> api.customer.v1.ListPhoneNumberReq
	20, // 10: api.customer.v1.Customer.ListEmail:input_type -> api.customer.v1.ListEmailReq
	0,  // 11: api.customer.v1.Customer.GetCustomer:input_type -> api.customer.v1.GetCustomerReq
	2,  // 12: api.customer.v1.Customer.GetCustomerByEmail:input_type -> api.customer.v1.GetCustomerByEmailReq
	4,  // 13: api.customer.v1.Customer.GetCustomerByPhoneNumber:input_type -> api.customer.v1.GetCustomerByPhoneNumberReq
	16, // 14: api.customer.v1.Customer.DeletePhoneNumber:input_type -> api.customer.v1.DeletePhoneNumberReq
	28, // 15: api.customer.v1.Customer.DeleteAddress:input_type -> api.customer.v1.DeleteAddressReq
	22, // 16: api.customer.v1.Customer.DeleteEmail:input_type -> api.customer.v1.DeleteEmailReq
	7,  // 17: api.customer.v1.Customer.CreateCustomer:output_type -> api.customer.v1.CreateCustomerReply
	19, // 18: api.customer.v1.Customer.CreateEmail:output_type -> api.customer.v1.CreateEmailReply
	13, // 19: api.customer.v1.Customer.CreatePhoneNumber:output_type -> api.customer.v1.CreatePhoneNumberReply
	9,  // 20: api.customer.v1.Customer.UpdateCustomer:output_type -> api.customer.v1.UpdateCustomerReply
	11, // 21: api.customer.v1.Customer.DeleteCustomer:output_type -> api.customer.v1.DeleteCustomerReply
	31, // 22: api.customer.v1.Customer.ListCustomer:output_type -> api.customer.v1.ListCustomerReply
	25, // 23: api.customer.v1.Customer.CreateAddress:output_type -> api.customer.v1.CreateAddressReply
	27, // 24: api.customer.v1.Customer.ListAddress:output_type -> api.customer.v1.ListAddressReply
	15, // 25: api.customer.v1.Customer.ListPhoneNumber:output_type -> api.customer.v1.ListPhoneNumberReply
	21, // 26: api.customer.v1.Customer.ListEmail:output_type -> api.customer.v1.ListEmailReply
	1,  // 27: api.customer.v1.Customer.GetCustomer:output_type -> api.customer.v1.GetCustomerReply
	3,  // 28: api.customer.v1.Customer.GetCustomerByEmail:output_type -> api.customer.v1.GetCustomerByEmailReply
	5,  // 29: api.customer.v1.Customer.GetCustomerByPhoneNumber:output_type -> api.customer.v1.GetCustomerByPhoneNumberReply
	17, // 30: api.customer.v1.Customer.DeletePhoneNumber:output_type -> api.customer.v1.DeletePhoneNumberReply
	29, // 31: api.customer.v1.Customer.DeleteAddress:output_type -> api.customer.v1.DeleteAddressReply
	23, // 32: api.customer.v1.Customer.DeleteEmail:output_type -> api.customer.v1.DeleteEmailReply
	17, // [17:33] is the sub-list for method output_type
	1,  // [1:17] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_customer_v1_customer_proto_init() }
func file_api_customer_v1_customer_proto_init() {
	if File_api_customer_v1_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_customer_v1_customer_proto_rawDesc), len(file_api_customer_v1_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_customer_v1_customer_proto_goTypes,
		DependencyIndexes: file_api_customer_v1_customer_proto_depIdxs,
		MessageInfos:      file_api_customer_v1_customer_proto_msgTypes,
	}.Build()
	File_api_customer_v1_customer_proto = out.File
	file_api_customer_v1_customer_proto_goTypes = nil
	file_api_customer_v1_customer_proto_depIdxs = nil
}
