// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"customer/internal/biz"
	"customer/internal/conf"
	"customer/internal/data"
	"customer/internal/server"
	"customer/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	customerRepo := data.NewCustomerRepo(dataData)
	customerUsecase := biz.NewCustomerUsecase(customerRepo)
	customerService := service.NewCustomerService(customerUsecase)
	grpcServer := server.NewGRPCServer(confServer, customerService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
